services:
  - type: web
    name: spotsync-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DSN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
